### ISSUE TITLE
Comptability with SQLAlchemy >1.4.0

### ISSUE THREAD

**Issue by AhmedBytesBits** [kolypto/py-mongosql#15]
Hi,
Thanks for the great project, it really saves a lot of time and gives room for more ideas. When I have tried to install it using Poetry it raises the following error:

```

  SolverProblemError

  Because no versions of mongosql match >2.0.15,<2.0.15.post1 || >2.0.15.post1,<3.0.0
   and mongosql (2.0.15) depends on sqlalchemy (>=1.2,<1.2.9 || >1.2.9,<1.4), mongosql (>=2.0.15,<2.0.15.post1 || >2.0.15.post1,<3.0.0) requires sqlalchemy (>=1.2,<1.2.9 || >1.2.9,<1.4).
  And because mongosql (2.0.15.post1) depends on sqlalchemy (>=1.2,<1.2.9 || >1.2.9,<1.4), mongosql (>=2.0.15,<3.0.0) requires sqlalchemy (>=1.2,<1.2.9 || >1.2.9,<1.4).
  So, because chat-bot depends on both SQLAlchemy (^1.4.37) and mongosql (^2.0.15), version solving failed.
```

Is it possible to upgrade the dependency to be ^1.4.37?

Please consider that SQLAlchemy current version is 1.4.39 and all versions before 1.3.24 are in EOL state

**Comment by kolypto** [comment]
Hi @ahmedrshdy , 
thanks for your interest in the library :) Currently, 1.4 won't work because it has a different relationship loading mechanism that will break MongoSQL. Most likely, I'll have to copy-paste the old implementation into MongoSQL :( 
At the moment, it just won't work. 

We'll probably make a fix, but it takes time.

**Comment by AhmedBytesBits** [comment]
oh, I understand now, thanks for getting back on this
