### ISSUE TITLE
order by column from another table

### ISSUE THREAD

**Issue by xenups** [kolypto/py-mongosql#8]
when i want to sort like this 
`query={"sort":"movie_rate.imdb_rate-"}
`its return this error
`Invalid column \"movie_rate.imdb_rate\" for \"Movie\" specified in sort
`
although i can filter with:
`query={"filter":"movie_rate.imdb_rate":5}
`
so how I can order by a column from another table

**Comment by kolypto** [comment]
Hi @xenups , thanks for your interest in the project :)
Currently, yes, `filter` can work with "related columns" (`rcol`):

![image](https://user-images.githubusercontent.com/2234216/95446241-b30aa480-0968-11eb-8758-ee02ebc7024b.png)

But `sort` can not: `rcol` is not supported:

![image](https://user-images.githubusercontent.com/2234216/95446303-c4ec4780-0968-11eb-9973-995923520700.png)

and it is not trivial to add, actually, because your related objects may not even be present in the query: SqlAlchemy may make a second query to fetch them (the so-called `selectinload`), and so it's not available for sorting.

It can be implemented, but will be a performance hit, because it requires joining a table just for the purpose of sorting.

With `filter`, the related columns are available using a sort of a trick:

if you filter by a related column:

> filter={'articles.id': 1}

it actually inserts this thing into the query:

> WHERE EXISTS (SELECT 1 FROM articles WHERE users.id = articles.uid AND articles.id = 1)

MongoSql is not supposed to be a full-featured replacement for SQL queries :) It's more like a tool that makes some aspects of UI development easier. 

In your case, you probably have to write a custom SqlAlchemy query, and feed it into MongoSQL.
Something like this:

> query = session.query(...).order_by(...)
> mongoquery = MongoQuery(...).from_query(query)

**Comment by xenups** [comment]
Hi kolypto thanks for your support, what I did after you said, Im, joining tables and using this way to sort 
```
    join: {
        posts: {
            sort: ['date-']
        }
```
